swagger: '2.0'
info:
  title: Modern Appraisal Mock API
  description: Modern Appraisal Mock API fro web and mobile
  version: "1.0.0"
schemes:
  - https
basePath: api/v1
produces:
  - application/json
paths:
  /questions:
    get:
      summary: "GET Questions list"
      description: |
        The Questions endpoint returns all appraisal form questions
      responses:
        200:
          description: An array of questions
          schema:
            type: array
            items:
              $ref: 'definitions/Question.yaml#/Question'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'

  /sections:
    get:
      summary: "Get List of sections"
      responses:
        200:
          schema:
            type: array
            items:
              $ref: 'definitions/Section.yaml#/Section'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'

  /sections/{sectionId}:
    get:
      summary: "Get section details"
      parameters:
        sectionId:
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          schema:
            $ref: 'definitions/Section.yaml#/Section'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'

  /answers/{facilityId}:
    get:
      summary: "GET answers for selected assignment"
      parameters:
        facilityId:
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          schema:
            $ref: 'definitions/AnswerGET.yaml#/Answer'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'
    post:
      summary: "Save answers"
      parameters:
        answers:
          in: body
          schema:
            type: object
            properties:
              protocol:
                $ref: 'definitions/Protocol.yaml#/Protocol'
              data:
                type: array
                items:
                  $ref: 'definitions/AnswerPOST.yaml#/Answer'
          required: true
      responses:
        200:
          schema:
            type: integer
        default:
          description: Unexpected error
          schema:
            $ref: 'definitions/Error.yaml#/Error'

  /answers/{facilityId}/section/{sectionId}:
    get:
      summary: "GET answers for section"
      parameters:
        facilityId:
          in: path
          schema:
            type: string
          required: true
        sectionId:
          in: path
          schema:
          type: string
          required: true
      responses:
        200:
          schema:
            $ref: 'definitions/AnswerGET.yaml#/Answer'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'

  /answers/{facilityId}/{questionId}:
    get:
      summary: "GET detailed answer with history for selected question"
      parameters:
        facilityId:
          in: path
          schema:
            type: string
          required: true
        questionId:
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          schema:
            $ref: 'definitions/Question.yaml#/Question'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'

  /users/{userId}:
    get:
      summary: "GET user info"
      parameters:
        userId:
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          schema:
            $ref: 'definitions/User.yaml#/User'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'

  /users/{userId}/assignments:
    get:
      summary: "GET user assignments"
      parameters:
        userId:
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          schema:
            type: array
            items:
              $ref: 'definitions/Assignment.yaml#/Assignment'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'
    post:
      parameters:
        body:
          type: object
          in: body
          schema:
            type: object
            properties:
              address:
                description: "Address from Google API"
                type: string
                x-chance-type: address
              latitude:
                description: "Location Latitude"
                x-chance-type: latitude
              longitude:
                description: "Location Longitude"
                x-chance-type: longitude

      responses:
        200:
          schema:
            $ref: 'definitions/Assignment.yaml#/Assignment'
        default:
          description: "Unexpected error"
          schema: 'definitions/Error.yaml#/Error'

  /users/{userId}/assignments/{assignmentId}:
    get:
      summary: "GET assignment details"
      parameters:
        userId:
          in: path
          schema:
            type: string
          required: true
        assignmentId:
          in: path
          schema:
            type: string
          required: true
      responses:
        200:
          schema:
            $ref: 'definitions/Assignment.yaml#/Assignment'
        default:
          description: "Unexpected error"
          schema:
            $ref: 'definitions/Error.yaml#/Error'

